# This file contains the database configuration
#
# History
#   2019-09-29. First edition by Zhenping

db_path = "C:\\Users\\zhenping\\Desktop\\trajectory_scanner\\db\\"
db_filename = 'picasso_traj.db'
table_name = 'trajectory_figs'

['sql_query']
create_traj_table = """
CREATE TABLE IF NOT EXISTS ? (
    id integer PRIMARY KEY,
    filename text NOT NULL,
    category INT,
    pollynet_station text,
    gdas1_station text,
    path text,
    start_time text,
    stop_time text,
    upload_time text,
    insert_time text
);
"""
insert_traj_entry = """
INSERT INTO ?(filename,category,pollynet_station,gdas1_station,path,start_time,stop_time,upload_time,insert_time)
VALUES(?,?,?,?,?,?,?,?,?)
"""
delete_entry = """
DELETE FROM ? WHERE filename=? AND pollynet_station=?
"""